"""AI-as-a-service layer: reads the resume and proposes clarifying questions specific
to its actual content, on top of the rule-based gaps from src/gap_detection.py (missing
dates, vague titles, unquantified bullets).

The rule-based layer stays local and catches known patterns; this layer catches whatever
is specific to this particular resume that a fixed rule set can't - an ambiguous scope of
responsibility, an unexplained gap between roles, a title that seems to mismatch the
described duties, and so on. If the LLM call fails, this falls back to rule-based-only
questions so the quiz step is never blocked on it being available.
"""
import os
from itertools import zip_longest

from openai import OpenAI

from src.gap_detection import (
    Gap,
    MAX_QUESTIONS,
    pad_with_generic,
    rule_based_gaps,
)

MODEL = os.environ.get("RESUFIT_MODEL", "gpt-4o-mini")
MAX_LLM_QUESTIONS = 4

SYSTEM_PROMPT = """You are a supportive, experienced resume coach helping identify what's
missing or unclear in a candidate's resume draft, beyond generic formatting issues. You will
be shown the draft and a list of questions a rule-based checklist has already generated for it.

Propose additional clarifying questions that are specific to what this particular resume
actually says - things a fixed checklist would not catch. Good examples: an ambiguous
scope of responsibility, an unexplained gap between roles, a title that seems mismatched
with the described duties, a claim that could be stronger with a concrete number (team size,
frequency, time saved, percentage improvement), or a skill mentioned once but never
substantiated elsewhere.

Phrase each question the way an encouraging mentor would ask it over coffee, not like an
interrogation: warm and specific, about one detail at a time rather than a compound question
that bundles several asks together.

Rules:
- Do not repeat or rephrase any of the already-generated questions.
- Ask about this resume specifically. Do not ask generic questions that would apply to
  any resume regardless of content.
- If you're asking for a number, ask for the real one. Never suggest the candidate estimate
  or guess a figure they don't actually know; if they don't have it, that's what skipping the
  question is for.
- Return one question per line, no numbering, no greeting, no extra commentary, just the
  questions themselves.
- Return at most {max_questions} questions. If there is genuinely nothing more worth
  asking, return nothing at all.
"""

USER_PROMPT = """Resume draft:
{draft}

Questions already generated by the rule-based checklist:
{existing_questions}

Propose additional content-specific clarifying questions."""


def _format_existing(existing: list[str]) -> str:
    if not existing:
        return "(none yet)"
    return "\n".join(f"- {q}" for q in existing)


def generate_content_questions(
    draft: str,
    existing_questions: list[str],
    client: OpenAI | None = None,
    model: str | None = None,
    max_questions: int = MAX_LLM_QUESTIONS,
) -> list[Gap]:
    client = client or OpenAI()
    response = client.chat.completions.create(
        model=model or MODEL,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT.format(max_questions=max_questions)},
            {"role": "user", "content": USER_PROMPT.format(
                draft=draft,
                existing_questions=_format_existing(existing_questions),
            )},
        ],
        temperature=0.4,
    )
    text = response.choices[0].message.content or ""
    lines = [line.strip("-• ").strip() for line in text.splitlines() if line.strip()]
    return [
        Gap(kind="content_specific", line_index=-1, evidence="", question=line)
        for line in lines[:max_questions]
    ]


def build_quiz_queue(
    draft: str,
    client: OpenAI | None = None,
    model: str | None = None,
) -> list[Gap]:
    """Blends rule-based gaps with LLM-generated, content-specific questions, capped
    at MAX_QUESTIONS and padded with generic questions if the combined total still
    falls short of MIN_QUESTIONS. Falls back to rule-based-only on any LLM failure."""
    rule_gaps = rule_based_gaps(draft)

    try:
        llm_gaps = generate_content_questions(
            draft,
            [gap.question for gap in rule_gaps],
            client=client,
            model=model,
        )
    except Exception:
        return pad_with_generic(rule_gaps)

    merged = [
        gap
        for round_ in zip_longest(rule_gaps, llm_gaps)
        for gap in round_
        if gap is not None
    ][:MAX_QUESTIONS]

    return pad_with_generic(merged)
